language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
provider: heroku
  api_key:
    secure: KAJrxMYQdM1VsNhg0Z9PSQlWAdQA3ib/wGJVz2V3tvOOthoXIM4zRLxiKudsQp9lRDw3nfu4TYhRmbrEFmpEuYUGhpzbFz7cQm5qREHmkAmBvvL5YIsUL5b9V55mkkxxZ6FP2C5iNHuf9qz4UFQdGI7DH4rgoWID4qpBnwi7iZ/HBa5yEPi2isCeUt5iK4dDNd3+iPQz913Cx+ZXGIWlVVZM/d+DxDJheFg00PJPCffRofqa3NwPV9SIb+nIpHqTyfq15gTt42pYsxZY52dQw+3H80wKRLwYXxu0rAPCEXiQoN6l+/IBVp9M8GHtN12tDj8suWKrDFaQpKCTCVQu/fsQ9KNGNlvUz+Tfqh64jeSKxIy/QPxcm7wBkcYU2RsIHRRLlD2ZhmaoNQ5caNjkGLslpwLSvbf95alqHosCCtMtAx7i7e8xYkG+Q0R9UDDDd5+uWpJNvU5d1M43bJtrM4EwDP6tuc3zX+3v4m0oIwyDBT6t4li2M17LBFwzMBOXIxPFE7Kf/dJxaNWPU1WUvI/Hy5mx6wo9xqgEqFs8/GgM2pf8LuaOxMTshM6SRl8jgmf8ipCmmFJUf/uTqQUiK2zQxDCS/4uDQGw9L0pXd9vpSD5Fm9xpPuhX0EeSJFttLC+ohhqLcx2t36of2Ru9mQidlQ+R7jEqhRYqJOIC2aI=
  app: counterproductive-developer